serving: 
  spec: "local"
  version: "19.04.1.0.0"
  release: "current"
  iam: "Aggregate Messaging Controller API"
  application: 
  - spec: "local"
    host: ""
    port: 7890
  - spec: "testing"
    host: ""
    port: 7890

    
    